### ISSUE TITLE
Timed out sending 'list_disk'

### ISSUE THREAD

**Issue by kevinzurek** [cloudfoundry-incubator/bosh-azure-cpi-release#241] opened 2017-02-13 19:42 UTC
### Versions (*please add them if you have more releases for this issue*)
CPI   Version: 20
BOSH  Version: 260.0.0
CF    Version: 6.21.1+6fd3c9f-2016-08-10
Diego Version: N/A - using PCF 1.7

### Environment
- Azure Environment:
  - [x] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureStack
  - [ ] Others:
- Location: East US
- Subscription ID: 40811243-97fc-4269-80d1-a34bc0d1b5d7
- Resource Group Name: preprodeast-rg
- VM Name: pstorepreprodeastcf-1437c260-7697-4227-a0a3-366dd9e31dae

### Issue Details
While doing a bosh deployment, we received error "Failed: Timed out sending 'list_disk' to 1437c260-7697-4227-a0a3-366dd9e31dae after 45 seconds". The nfs VM was then placed in a stopped state. To fix this we had to manually reboot the nfs VM and restart the deployment.

At the time this happened there was an orphaned disk for the nfs instance.

### Logs (*Please redact all sensitive information in your logs*)
D, [2017-02-13 16:42:36 #57487] [] DEBUG -- DirectorJobRunner: (0.054204s) UPDATE "locks" SET "expired_at" = '2017-02-13 16:42:47.355693+0000' WHERE (("name" = 'lock:deployment:cf-deployment') AND ("uid" = '7872b5a0-0788-416c-a014-8d67554e9b27'))

E, [2017-02-13 16:42:36 #57487] [canary_update(nfs/279571fa-0fb7-4441-9408-7b912e02564a (0))] ERROR -- DirectorJobRunner: Error updating canary instance: #<Bosh::Director::RpcTimeout: Timed out sending 'list_disk' to 1437c260-7697-4227-a0a3-366dd9e31dae after 45 seconds>

/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/agent_client.rb:238:in `block in handle_method'

**Comment by AbelHu** [comment] 2017-02-14 01:52
@kevinzurek Sorry for that we missed the stemcell name and version in the issue template. What is your stemcell name and version? Did the error occur when preparing to attach the persistent data disk after recreating the NFS VM? If so, I guess that this error occurred because the data disk was not attached to the VM in 45 seconds so it expired when bosh-agent inside the NFS VM were executing `list_disk`.

Could you send below logs to us azcfchina@microsoft.com for advanced investigation? 
1. Your update task logs: `bosh task YOUR-FAILED-TASK-ID --debug > failed.log`
2. The bosh-agent logs inside the NFS VM: `/var/vcap/bosh/log/*`

**Comment by kevinzurek** [comment] 2017-02-14 18:45
Hi @AbelHu ,

The stemcell version is "bosh-azure-hyperv-ubuntu-trusty-go_agent/3233.9".  We increased the size of the persistent disk on this particular VM last Friday and it seems that the default behavior of bosh is to leave the old disk orphaned for 5 days before cleaning up. We didn't experience any issues with this - i was adding it as additional information, though.

Logs sent! Thank you!

**Comment by AbelHu** [comment] 2017-02-15 06:18
@kevinzurek We are investigating this issue. Please copy the persistent data disk (It is a blob in the storage account whose name the disk name starts with) to other container to avoid BOSH deletes it.

**Comment by kevinzurek** [comment] 2017-02-15 15:57
@AbelHu the orphaned disk was manually deleted while we were troubleshooting. The disk that replaced it is currently attached and seems to be performing fine. 

I am cleaning up the update task logs and will send this afternoon. Thanks!

**Comment by AbelHu** [comment] 2017-02-17 07:39
@kevinzurek We reproduced this issue and filed an issue [#120](https://github.com/cloudfoundry/bosh-agent/issues/120) for bosh-agent.

**Comment by kevinzurek** [comment] 2017-02-20 14:56
You are correct that the orphaned disk is the old disk. The data was migrated and attached to the new disk, but the new deployment afterwards caused the timeout issue. 

Thank you for your help @AbelHu  :+1:

**Comment by AbelHu** [comment] 2017-02-28 00:10
Below this issue is fixed by bosh, you can use below workaround if you hit this issue.

1. Execute `bosh ssh` in your dev-box to the VM which this issue occurred
1. Execute `sudo su`
1. Execute `cd /var/vcap/bosh`
1. Execute `grep -rnw log -e 'endpoint'`, you can find similar content as below

    ```
    {"registry":{"endpoint":"http://admin:PASSWORD@10.0.0.4:25777"},"server":{"name":"jkrp62yeysvgkcfdefaultsa-bcff1a53-fba5-4965-8782-562189a09574"},"dns":{"nameserver":["168.63.129.16","8.8.8.8","10.0.0.4"]}}
    ```
1. Execute `curl -k REGISTRY-ENDPOINT/instances/INSTANCE-ID/settings > /var/vcap/bosh/new_settings.json`
    - Replace `REGISTRY-ENDPOINT` with the value of above `registry.endpoint`
    - Replace `INSTANCE-ID` with the value of above `server.name`
1. Please reference `/var/vcap/bosh/new_settings.json` to update your `/var/vcap/bosh/settings.json`
1. Execute `bosh -n deploy` in your dev-box

**Comment by kevinzurek** [comment] 2017-03-15 12:03
Hi @AbelHu 

By default, bosh keeps orphaned disks for 5 days. It was during that 5 day period that this issue was experienced.

Am i correct to think that, after (5 days) bosh cleans up the orphaned disk, bosh-agent will fetch the proper settings and this will not occur?

**Comment by AbelHu** [comment] 2017-03-15 23:38
@kevinzurek I think whether bosh-agent will fetch the proper settings from bosh-registry depends on that load_settings is called. I think this should have been fixed. You can see it in this [commit](https://github.com/cloudfoundry/bosh-agent/commit/90a427a39bcd2882543ac5fe5818a516feca9b5b).

**Comment by AbelHu** [comment] 2017-04-06 04:21
This issue has been fixed in the latest stemcell.

**Closed by AbelHu** 2017-04-06 04:21 UTC
Labels: acknowledge
