### ISSUE TITLE
Create stemcell not failing when bucket dosen't exist

### ISSUE THREAD

**Issue by tinygrasshopper** [cloudfoundry-incubator/bosh-azure-cpi-release#208] opened 2016-09-19 15:45 UTC
**Scenario:**
There is no container named `stemcell` in my storage account, and I upload stemcell using the cli

**Current Result:**
the `create_stemcell` cpi call returns success even, without uploading any stemcell, as a result the next call, i.e. create instance starts to fail

**Desired Result:**
the create_stemcell call fails, if it cant upload, and informs the operator what is wrong

**Comment by AbelHu** [comment] 2016-09-19 22:21
@tinygrasshopper This is a known issue which is caused by a bug in azure-ruby-asm-core. It has been fixed in this [commit](https://github.com/Azure/azure-ruby-asm-core/commit/d4c9e4ff8ccd0d1aecca6e97519621b477aa0eb9). Next Azure CPI will use the latest azure-ruby-asm-core. You can see this [commit](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/commit/301785cea53e95ec24a630d90d0746c2e467ece8)

**Closed by AbelHu** 2016-09-19 22:21 UTC
Labels: acknowledge, Done
