### ISSUE TITLE
Flakiness on copying stemcells to other storage accounts

### ISSUE THREAD

**Issue by dsboulder** [cloudfoundry-incubator/bosh-azure-cpi-release#194] opened 2016-08-19 19:15 UTC
When I tried to boot 10 VMs at once on CPI v14, I see the following exception:

```
  Started creating missing vms
  Started creating missing vms > consul_server/0 (b082d457-5363-4d47-b860-a0d6f06d5be5)
  Started creating missing vms > nats/0 (7b4b95c7-e2cf-4d98-b574-2d89130783ca)
  Started creating missing vms > etcd_server/0 (eef7d734-486c-41e3-b710-ac8a6ed24d74)
  Started creating missing vms > diego_database/0 (06678a03-9fa2-4a96-80be-e8aaa72c4514)
  Started creating missing vms > nfs_server/0 (782d8150-153f-4f4d-9209-704127edacb7)
  Started creating missing vms > mysql_proxy/0 (2562fb2c-0944-49b3-aab7-07786401b9e5)
  Started creating missing vms > mysql/0 (94e643d1-3d19-4f4b-aa71-28926f22c678)
  Started creating missing vms > uaa/0 (f457bb84-e879-4b91-987f-70caa72bf955)
  Started creating missing vms > cloud_controller/0 (d8ac8dae-c5a3-4bf8-bf7c-e0ce76d108b7)
  Started creating missing vms > ha_proxy/0 (ec799571-7d6e-4eb5-8b22-6378aad37192)
   Failed creating missing vms > mysql/0 (94e643d1-3d19-4f4b-aa71-28926f22c678): Cannot find the stemcell bosh-stemcell-84a9f90a-9ad4-4d23-abc8-babc7dd1fa7b in the table stemcells in the default storage account dsomaug18storageaccount (00:00:08)
   Failed creating missing vms > mysql_proxy/0 (2562fb2c-0944-49b3-aab7-07786401b9e5): Cannot find the stemcell bosh-stemcell-84a9f90a-9ad4-4d23-abc8-babc7dd1fa7b in the table stemcells in the default storage account dsomaug18storageaccount (00:00:08)
   Failed creating missing vms > etcd_server/0 (eef7d734-486c-41e3-b710-ac8a6ed24d74): Cannot find the stemcell bosh-stemcell-84a9f90a-9ad4-4d23-abc8-babc7dd1fa7b in the table stemcells in the default storage account dsomaug18storageaccount (00:00:08)
   Failed creating missing vms > diego_database/0 (06678a03-9fa2-4a96-80be-e8aaa72c4514): insert_entity: #<RuntimeError: Xml is not a entry node.>
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/azure-storage-0.10.2.preview/lib/azure/storage/service/serialization.rb:297:in `expect_node'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/azure-storage-0.10.2.preview/lib/azure/storage/table/serialization.rb:102:in `hash_from_entry_xml'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/azure-storage-0.10.2.preview/lib/azure/storage/table/table_service.rb:220:in `insert_entity'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/table_manager.rb:54:in `insert_entity'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/stemcell_manager.rb:110:in `handle_stemcell_in_different_storage_account'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/stemcell_manager.rb:69:in `has_stemcell?'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:107:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_common-1.3262.4.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:104:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:35:in `<main>' (00:00:09)
```

When I retried the deployment, things worked correctly the 2nd time.  Maybe there is a race condition?  I'll email Abel with my debug log directly so he can look into it.  The debug log shows entries like this:

```
I, [2016-08-19T16:53:33.627196 #3532]  INFO -- : http_post - 0: trying to post https://management.azure.com//subscriptions/b269df04-a1d5-4e2b-9368-d4abf33bc411/resourceGroups/dsomaug18-pcf-resource-group/providers/Microsoft.Storage/storageAccounts/dsomaug18ompremium/listKeys?api-version=2015-06-15
D, [2016-08-19T16:53:33.627330 #3532] DEBUG -- : http_get_response - 0: #<Net::HTTP::Post POST>, URI: https://management.azure.com//subscriptions/b269df04-a1d5-4e2b-9368-d4abf33bc411/resourceGroups/dsomaug18-pcf-resource-group/providers/Microsoft.Storage/storageAccounts/dsomaug18ompremium/listKeys?api-version=2015-06-15
D, [2016-08-19T16:53:33.978810 #3532] DEBUG -- : http_get_response - 0: 200, request id: 3f7a3ddf-8209-4d37-8b3e-80105fa8dbaf, correlation id: 3f7a3ddf-8209-4d37-8b3e-80105fa8dbaf, routing id: WESTUS:20160819T165333Z:3f7a3ddf-8209-4d37-8b3e-80105fa8dbaf, response.body cannot be logged because it may contain credentials.
D, [2016-08-19T16:53:33.978873 #3532] DEBUG -- : check_completion - azure-asyncoperation: 
I, [2016-08-19T16:53:34.052026 #3532]  INFO -- : Copy id: 2192798a-9e0e-49f1-9d6e-c602a6b196f8, copy status: pending
D, [2016-08-19T16:53:34.134320 #3532] DEBUG -- : Copying progress: 0/3221225984
D, [2016-08-19T16:53:39.152761 #3532] DEBUG -- : Copying progress: 0/3221225984
D, [2016-08-19T16:53:44.171524 #3532] DEBUG -- : Copying progress: 0/3221225984
D, [2016-08-19T16:53:49.189041 #3532] DEBUG -- : Copying progress: 0/3221225984
D, [2016-08-19T16:53:54.210445 #3532] DEBUG -- : Copying progress: 157286400/3221225984
D, [2016-08-19T16:54:24.229930 #3532] DEBUG -- : Copying progress: 629145600/3221225984
D, [2016-08-19T16:54:54.249196 #3532] DEBUG -- : Copying progress: 1010827264/3221225984
D, [2016-08-19T16:55:24.267923 #3532] DEBUG -- : Copying progress: 2359296000/3221225984
I, [2016-08-19T16:55:54.305130 #3532]  INFO -- : Copy the blob https://dsomaug18storageaccount.blob.core.windows.net/stemcell/bosh-stemcell-84a9f90a-9ad4-4d23-abc8-babc7dd1fa7b.vhd successfully. Duration: 140.325928184
I, [2016-08-19T16:55:54.305274 #3532]  INFO -- : query_entities(stemcells, {:filter=>"PartitionKey eq 'bosh-stemcell-84a9f90a-9ad4-4d23-abc8-babc7dd1fa7b' and RowKey eq 'dsomaug18ompremium'"})
E, [2016-08-19T16:55:54.353118 #3532] ERROR -- : Cannot find the stemcell record bosh-stemcell-84a9f90a-9ad4-4d23-abc8-babc7dd1fa7b:dsomaug18ompremium in the table stemcells in the default storage account dsomaug18storageaccount
I, [2016-08-19T16:55:54.353247 #3532]  INFO -- : delete_entity(stemcells, bosh-stemcell-84a9f90a-9ad4-4d23-abc8-babc7dd1fa7b, dsomaug18ompremium)
I, [2016-08-19T16:55:54.377543 #3532]  INFO -- : delete_blob(dsomaug18ompremium, stemcell, bosh-stemcell-84a9f90a-9ad4-4d23-abc8-babc7dd1fa7b.vhd)
, exit_status: pid 3532 exit 0
E, [2016-08-19 16:55:54 #2812] [create_missing_vm(ha_proxy/0 (ec799571-7d6e-4eb5-8b22-6378aad37192)/19)] ERROR -- DirectorJobRunner: error creating vm: Cannot find the stemcell record bosh-stemcell-84a9f90a-9ad4-4d23-abc8-babc7dd1fa7b:dsomaug18ompremium in the table stemcells in the default storage account dsomaug18storageaccount
```

**Comment by AbelHu** [comment] 2016-08-22 02:09
@dsboulder This issue was caused by that Azure returns an invalid response and azure-storage-ruby does not handle it correctly. This issue is hard to reproduce because current azure-storage-ruby does not log routing id and request id for the investigation on Azure side. After azure-storage-ruby fixes this issue, CPI will use the new one.
For now you can enable debug_mode by setting it to true in your bosh.yml. If you hit this issue again, you can send the Azure HTTP raw response to us for trouble shooting.

**Comment by cppforlife** [comment] 2016-09-07 20:47
@AbelHu @dsboulder this seems like a very hard way to debug. i think cpi should include whatever necessary information needed by default.

**Comment by AbelHu** [comment] 2016-09-08 05:29
@cppforlife Agree. We will investigate how to do it.
@dsboulder Could you send below information for us to ask storage team to check Azure logs?

1. The default storage account name(Table was created under this storage account)
2. Location
3. Timestamp when the error occurred.

**Comment by AbelHu** [comment] 2016-09-15 18:42
@cppforlife @dsboulder I have created a [PR ](https://github.com/Azure/azure-storage-ruby/pull/51) for azure-storage-ruby. It can log more information in the exception if the response is invalid.

**Comment by AbelHu** [comment] 2016-09-22 00:43
When Azure returns a failed response, azure-ruby-asm-core still continues to handle the body of the response. Because the body is empty, it always throws '#<RuntimeError: Xml is not a entry node.>' .

Above issue in azure-ruby-asm-core was fixed in this [commit ](https://github.com/Azure/azure-ruby-asm-core/commit/1660d3f5deaa7dd7dde626705d3a254392ccde57).

So if Azure returns a failed response next time, we should be able to get the error message.

**Comment by AbelHu** [comment] 2016-10-10 02:40
Close it since azure-ruby-asm-core has fixed the issue.

**Closed** 2016-10-10 02:46 UTC
Labels: Done
