### ISSUE TITLE
BOSH CLI fails to deploy BOSH Director with instance_type STANDARD_D2_V2

### ISSUE THREAD

**Issue by cunnie** [cloudfoundry-incubator/bosh-azure-cpi-release#227] opened 2016-12-01 15:43 UTC
[BOSH CLI](https://github.com/cloudfoundry/bosh-cli) fails to deploy BOSH Director with instance_type `STANDARD_D2_V2`:

```
$ bosh create-env bosh-azure.yml -l <(lpass show --note deployments)
...
    ```
    Deploying:
      Creating instance 'bosh/0':
        Updating instance disks:
          Updating disks:
            Deploying disk:
              Mounting disk:
                Sending 'get_task' to the agent:
                  Agent responded with error: Action Failed get_task: Task 0304721e-6211-4fb3-642c-0754b6fc8ece result: Persistent disk with volume id 'bosh-data-cunniestore-f8511a5c-c154-43f3-aa07-4b3d6229bb84-None' could not be found

    Exit code 1
```

[Manifest of failed deploy](https://github.com/cunnie/deployments/blob/82841f329dd43b99a4c38946414f41e84a03027e/bosh-azure.yml#L21)

Deployment succeeds if `instance_type` is set to `STANDARD_D1`

IIRC, persistent disk was properly attached at `/dev/sdd` but was not mounted to `/var/vcap/store`

Also, I was deploying to Southeast Asia — not sure if that's a significant factor. This is not an important problem for me, but I want to let you know it's occurring, @abelhu

**Comment by AbelHu** [comment] 2016-12-01 23:54
@cunnie Could you still repro this issue now? If so, could you send partial logs for above two failures to me (chou.hu@microsoft.com) for investigation?

**Comment by AbelHu** [comment] 2016-12-05 02:51
@cunnie We can reproduce the issue and are investigating it.

**Comment by AbelHu** [comment] 2016-12-05 09:15
@cunnie This issue only happens when the stemcell version is greater than 3306. When bosh-agent executes `mke2fs -t ext4 -j -E lazy_itable_init=1 /dev/sdc2` before mounting the ephemeral disk, it takes ~6m36s when using Standard_D2_v2. The SSH tunnel from bosh_cli to BOSH director VM is disconnected when using stemcell 3308 or later so that bosh-agent cannot get the VM settings from bosh-registry.

@cppforlife Do you have any idea about the code change in stemcell for above issue?

**Comment by cppforlife** [comment] 2016-12-05 17:43
@AbelHu I'm not aware of any change that went in. Also it appears that bats on CPI for 3312 are passing. Is this related to a specific instance type?

**Comment by cppforlife** [comment] 2016-12-05 17:43
cc @dsboulder seen any problems like this?

**Comment by dsboulder** [comment] 2016-12-05 18:56
No, but I always use DSv2 (not v1) so maybe there's something up with that original D series?

**Comment by sunjayBhatia** [comment] 2016-12-05 22:51
@natalieparellano and i saw this when we attempted to deploy a director using the `Standard_D4` VM size. We were able to see the disk exist in the Azure portal when it failed to attach. We were able to successfully deploy a director with `Standard_D1` - `Standard_D3`. Below is a screenshot of the error output:
![screen shot 2016-12-05 at 3 02 33 pm](https://cloud.githubusercontent.com/assets/5337253/20905796/49c5cee8-bb13-11e6-9b5c-dbe42642e24b.png)

**Comment by AbelHu** [comment] 2016-12-06 01:45
This issue only occurs in some VM sizes when the formatting takes a long time with using the stemcell v3308 or later.
You can try stemcell v3306.

**Comment by cppforlife** [comment] 2016-12-06 01:48
@AbelHu i dont think we can recommend people to downgrade to 3306. also if that's the case how does the bats pass with 3312?

**Comment by AbelHu** [comment] 2016-12-06 01:51
@cppforlife We are investigating it. Will update you soon.

**Comment by AbelHu** [comment] 2016-12-06 09:11
@cppforlife From stemcell v3308, the system seems like to be frozen when executing `mke2fs -t ext4 -j -E lazy_itable_init=1 /dev/sdc2` until the command is finished. 

You can see below logs. Every 5 seconds, bosh-agent runs a command `arping -c 1 -U -I eth0 10.0.0.4`. But there is no any log between `2016-12-06_08:50:44.31306` and `2016-12-06_08:57:20.01879`.

Partial logs:
```
2016-12-06_08:49:17.19532 [Cmd Runner] 2016/12/06 08:49:17 DEBUG - Running command 'mke2fs -t ext4 -j -E lazy_itable_init=1 /dev/sdc2'
2016-12-06_08:49:19.05940 [Cmd Runner] 2016/12/06 08:49:19 DEBUG - Running command 'arping -c 1 -U -I eth0 10.0.0.4'
2016-12-06_08:49:19.07051 [Cmd Runner] 2016/12/06 08:49:19 DEBUG - Stdout: ARPING 10.0.0.4 from 10.0.0.4 eth0
2016-12-06_08:49:19.07052 Sent 1 probes (1 broadcast(s))
2016-12-06_08:49:19.07053 Received 0 response(s)
2016-12-06_08:49:19.07053 [Cmd Runner] 2016/12/06 08:49:19 DEBUG - Stderr:
2016-12-06_08:49:19.07053 [Cmd Runner] 2016/12/06 08:49:19 DEBUG - Successful: true (0)
2016-12-06_08:49:24.07168 [Cmd Runner] 2016/12/06 08:49:24 DEBUG - Running command 'arping -c 1 -U -I eth0 10.0.0.4'
2016-12-06_08:49:24.08264 [Cmd Runner] 2016/12/06 08:49:24 DEBUG - Stdout: ARPING 10.0.0.4 from 10.0.0.4 eth0
2016-12-06_08:49:24.08265 Sent 1 probes (1 broadcast(s))
2016-12-06_08:49:24.08265 Received 0 response(s)
2016-12-06_08:49:24.08265 [Cmd Runner] 2016/12/06 08:49:24 DEBUG - Stderr:
2016-12-06_08:49:24.08266 [Cmd Runner] 2016/12/06 08:49:24 DEBUG - Successful: true (0)

.............

2016-12-06_08:50:39.28687 [Cmd Runner] 2016/12/06 08:50:39 DEBUG - Running command 'arping -c 1 -U -I eth0 10.0.0.4'
2016-12-06_08:50:39.30066 [Cmd Runner] 2016/12/06 08:50:39 DEBUG - Stdout: ARPING 10.0.0.4 from 10.0.0.4 eth0
2016-12-06_08:50:39.30068 Sent 1 probes (1 broadcast(s))
2016-12-06_08:50:39.30068 Received 0 response(s)
2016-12-06_08:50:39.30068 [Cmd Runner] 2016/12/06 08:50:39 DEBUG - Stderr:
2016-12-06_08:50:39.30068 [Cmd Runner] 2016/12/06 08:50:39 DEBUG - Successful: true (0)
2016-12-06_08:50:44.30112 [Cmd Runner] 2016/12/06 08:50:44 DEBUG - Running command 'arping -c 1 -U -I eth0 10.0.0.4'
2016-12-06_08:50:44.31304 [Cmd Runner] 2016/12/06 08:50:44 DEBUG - Stdout: ARPING 10.0.0.4 from 10.0.0.4 eth0
2016-12-06_08:50:44.31305 Sent 1 probes (1 broadcast(s))
2016-12-06_08:50:44.31306 Received 0 response(s)
2016-12-06_08:50:44.31306 [Cmd Runner] 2016/12/06 08:50:44 DEBUG - Stderr:
2016-12-06_08:50:44.31306 [Cmd Runner] 2016/12/06 08:50:44 DEBUG - Successful: true (0)
2016-12-06_08:57:20.01879 [Cmd Runner] 2016/12/06 08:57:20 DEBUG - Stdout: Discarding device blocks:    4096/6078594
^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H               ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^Hdone
2016-12-06_08:57:20.01882 Filesystem label=
2016-12-06_08:57:20.01882 OS type: Linux
2016-12-06_08:57:20.01882 Block size=4096 (log=2)
```

**Comment by cppforlife** [comment] 2016-12-06 09:20
how about doing strace on mke2fs?

**Comment by cunnie** [comment] 2016-12-12 19:40
@AbelHu FYI, although we don't have a clear fix of the problem, this is what we have discovered so far:

* We suspect that the `Persistent disk with volume id 'bosh-data-cunniestore` is related to an excessively-time-consuming (**~8 minutes**) formatting of the ephemeral disk (i.e. `time mke2fs -t ext4 -j -E lazy_itable_init=1 /dev/sdc2`
  * Disabling Azure Disk Host Caching did not have any effect.
  * Kubernetes has a [similar issue](https://github.com/kubernetes/kubernetes/issues/30752#issuecomment-261303142)
  * Once the disk has been successfully formatted, the problem disappears. Repeated formatting (`mke2fs`) on the same volume completes in seconds.
  * The problem only seems to manifest on Ubuntu machines running on a 4.4 kernel; an almost identical deployment with a 3.19 kernel did not have that problem. We used stemcells 3262.22 (linux 3.19) and 3263.8 (linux 4.4). The 2 stemcells are almost identical with the exception of the kernel version.
  * Our [Tracker Story](https://www.pivotaltracker.com/story/show/135798181) has very detailed description of our debugging attempts.

**Comment by AbelHu** [comment] 2016-12-13 01:55
@cunnie Thanks for the sharing result. We have involved our Linux expert to investigate this issue in our side.

**Comment by AbelHu** [comment] 2016-12-13 08:25
@cunnie @cppforlife It seems like to be caused by kernel 4.4. 
We created a Standard_D2_v2 with Ubuntu 14.04.5 and attached an empty data disk (Size: 100GB) to it on Azure. Then we used `fdisk` with below command and executed `mke2f2`. All commands finish in seconds.

```
echo -e 'n\n\n\n\n+6967M\nt\n82\nn\n\n\n\n\nw\n' | fdisk /dev/sdc
```
Old command:
```
sfdisk -uM /dev/sdc
,6967,S
,,L

y
```

**Comment by khuddlefish** [comment] 2016-12-13 19:47
@AbelHu, Our investigation seems to indicate that sfdisk isn't necessarily the problem. We created a 100GB disk, attached it to our VM, partitioned it via sfdisk, formatted it via mke2fs, and observed that the commands completed within seconds rather than the expected 8+ minutes. 
```
 # echo -e ',6967,S\n,,L' | sfdisk /dev/sde -uM
Checking that no-one is using this disk right now ...
OK

Disk /dev/sde: 13054 cylinders, 255 heads, 63 sectors/track

sfdisk: ERROR: sector 0 does not have an msdos signature
 /dev/sde: unrecognized partition table type
Old situation:
No partitions found
New situation:
Units = mebibytes of 1048576 bytes, blocks of 1024 bytes, counting from 0

   Device Boot Start   End    MiB    #blocks   Id  System
/dev/sde1         0+  6973-  6974-   7140892   82  Linux swap / Solaris
/dev/sde2      6973+ 102398- 95426-  97715362+  83  Linux
/dev/sde3         0      -      0          0    0  Empty
/dev/sde4         0      -      0          0    0  Empty
Warning: no primary partition is marked bootable (active)
This does not matter for LILO, but the DOS MBR will not boot this disk.
Successfully wrote the new partition table

Re-reading the partition table ...

If you created or changed a DOS partition, /dev/foo7, say, then use dd(1)
to zero the first 512 bytes:  dd if=/dev/zero of=/dev/foo7 bs=512 count=1
(See fdisk(8).)
 # time  mke2fs -t ext4 -j -E lazy_itable_init=1 /dev/sde1
mke2fs 1.42.9 (4-Feb-2014)
Discarding device blocks: done
Filesystem label=
OS type: Linux
Block size=4096 (log=2)
Fragment size=4096 (log=2)
Stride=0 blocks, Stripe width=0 blocks
447040 inodes, 1785223 blocks
89261 blocks (5.00%) reserved for the super user
First data block=0
Maximum filesystem blocks=1828716544
55 block groups
32768 blocks per group, 32768 fragments per group
8128 inodes per group
Superblock backups stored on blocks:
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done
Writing inode tables: done
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done


real	0m0.851s
user	0m0.020s
sys	0m0.112s
```

**Comment by AbelHu** [comment] 2016-12-13 23:39
@khuddlefish What is your VM size? We also cannot hit this issue in d1 and d3

**Comment by khuddlefish** [comment] 2016-12-14 00:43
@AbelHu : Standard D2 v2 (2 cores, 7 GB memory)

**Comment by khuddlefish** [comment] 2016-12-14 01:14
@AbelHu We'd like to summarize what we've discovered in the last two days while trying different approaches:

### Persistent Disk Could Not Be Found

* A deployment to Azure via the BOSH CLI may fail with `Persistent disk with volume id ... could not be found`
* One problem is that the ssh session from the VM to the workstation is prematurely terminated. We suspect that this may be due to a change in `bosh-agent`.  We believe the BOSH Core team is investigating. This appears to affect stemcells new than 3306.

### mke2fs takes 8+ minutes instead of seconds

* The problem is that mke2fs takes 8 minutes when it should only take a couple of seconds.
* The problem only occurs on certain instance types. e.g. It happens on Standard D2v2 but not Standard D1.
* The problem appears to only affect stemcells with the 4.4 kernels, not the 3.19 kernels (e.g. it affects the 3263.x and 33xx stemcells, but not the 3262.xx
* We have only checked the Ubuntu stemcells; we have not done any testing with the CentOS stemcells.
* As mentioned, passing -D to mke2fs cuts the time in half (3+ minutes).
* The problem doesn't appear if you `mke2fs` the same filesystem a 2nd time — the second one completes within seconds. We needed to do the following to reset to a broken state while debugging:
```
sudo dd if=/dev/zero of=/dev/sdc count=1 # clear MBR
sudo dd if=/dev/zero of=/dev/sdd count=1 # clear MBR
sudo dd if=/dev/zero of=/dev/sdc2 count=1000 # wipe fs
sudo dd if=/dev/zero of=/dev/sdd1 count=1000 # wipe fs
echo b > /proc/sysrq-trigger # force reboot

```
* We suspect that this contributes to the persistent disk not being found problem
* We ruled out a series of things which did _not_ help:

sysctl.conf
```
vm.swappiness=10
vm.dirty_ratio=80
vm.dirty_background_ratio = 50
```
rc.local
```
echo 0 > /sys/block/sda/queue/add_random
echo 0 > /sys/block/sda/queue/rotational
```
grub.conf (kernel parameters
```
elevator=noop
libata.force=noncq
```
mke2fs
```
-E discard
-E nodiscard
-E lazy_itable_init=0,lazy_journal_init=0 # took 20+ minutes!!
```

-- @cunnie and @khuddlefish

**Comment by ljfranklin** [comment] 2016-12-14 02:36
@AbelHu I think we're running out of stuff to try on our end and are hoping to throw the issue over to the Microsoft team from here. Would it be possible to loop some additional Azure folks that might have more visibility into what's going on here?

**Comment by AbelHu** [comment] 2016-12-14 02:37
@khuddlefish Please try to use sfdisk to format sde2 but not sde1. It is in seconds to format the first partition.

**Comment by AbelHu** [comment] 2016-12-14 02:38
@ljfranklin Yes. Actually we have involved our Linux expert to help to investigate this issue.

**Comment by AbelHu** [comment] 2016-12-14 02:43
@ljfranklin @cppforlife Could we use `fdisk` but not `sfdisk` in bosh-agent? Our Linux expert also indicated that as below.

"
**We’ve seen other issues with sfdisk in the Azure agent and cloud-init as well.  The old version was unmaintained (which is still in 14.04), and since a couple years ago has been under new management.  A lot of changes made and old options have been deprecated, for example the “sfdisk -uM …” syntax as described on that github bug doesn’t even work anymore in Ubuntu 16.04+.**
"

**Comment by ljfranklin** [comment] 2016-12-14 02:50
@cunnie @khuddlefish I'm a bit confused by your comment [here](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/issues/227#issuecomment-266841891). This comment indicates that y'all didn't think `sfdisk` was the cause of the issue. Did we confirm that switching `sfdisk` for `fdisk` had no effect?

**Comment by cppforlife** [comment] 2016-12-14 04:40
to clarify there are two issues at play here:

a. with 4.4 kernel there is non negligible delay to sfdisk partitioning

  - abel hopeully can give us some confirmation if switching to parted partitioner is ok and works on prollblem instance types

b. connection breakage between bosh-init and agent

  - somehow ssh tunnel is consistently terminated even if its in use, hence agent cannot fetch updated settings info from registry
    - i am trying to diagnose root cause for this problem but i think it can be considered independent problem that just happens to be triggered consistently if bootstrapping takes >8 min

**Comment by khuddlefish** [comment] 2016-12-14 18:07
Hi @AbelHu, sorry for the confusion on our end. We re-ran your suggestion to replace `sfdisk` with `fdisk` and you are correct that `sfdisk` seems to be the cause of the slowness. As you noted, in our previous experiment we accidentally ran `mke2fs` against the swap partition... We'll follow up with the BOSH Core team about switching the agent over to `fdisk`. Thanks for your help debugging!

**Comment by khuddlefish** [comment] 2016-12-14 18:50
Story in Core backlog is here: https://www.pivotaltracker.com/story/show/136133401

**Comment by ljfranklin** [comment] 2016-12-15 17:05
Confirmed that [stemcell 3312.9](https://s3.amazonaws.com/bosh-core-stemcells/azure/bosh-stemcell-3312.9-azure-hyperv-ubuntu-trusty-go_agent.tgz) boots up nice and fast with `Standard_D2_V2` instance:

```
Creating VM for instance 'bosh/0' from stemcell 'bosh-stemcell-5ba36367-ba59-4f1f-b9a9-f0322e7a5099'... Finished (00:01:42)
  Waiting for the agent on VM 'lfcdtest-5a741c78-3f50-4aca-52b6-89ec670c30c7' to be ready... Finished (00:00:26)
  Attaching disk 'bosh-data-lfcdtest-6de30b70-206d-42ec-baf1-0cf6f95289da-None' to VM 'lfcdtest-5a741c78-3f50-4aca-52b6-89ec670c30c7'... Finished (00:00:37)
```

@cunnie @AbelHu @cppforlife are we good to close this out?

**Comment by cppforlife** [comment] 2016-12-15 17:18
not yet, there is still bosh-init connection issue that im continuing to investigate.

**Comment by AbelHu** [comment] 2016-12-20 05:26
@cppforlife We cannot reproduce below issue with the latest new stemcell 3312.9. Could we close this issue for now? 

---
b. connection breakage between bosh-init and agent

  - somehow ssh tunnel is consistently terminated even if its in use, hence agent cannot fetch updated settings info from registry
    - i am trying to diagnose root cause for this problem but i think it can be considered independent problem that just happens to be triggered consistently if bootstrapping takes >8 min
---

**Comment by svrc-pivotal** [comment] 2017-03-14 19:17
seeing this with 3233.x (3233.9, 3233.12)

**Comment by AbelHu** [comment] 2017-03-14 23:54
@svrc-pivotal I cannot find 3233.x in [bosh GitHub repo](https://github.com/cloudfoundry/bosh/releases?after=stable-3262.4) and [bosh.io](http://bosh.io/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent).
@cppforlife Do you have any idea about the issue with 3233.x?

**Comment by cppforlife** [comment] 2017-03-15 00:08
@AbelHu ?all=1 (https://bosh.io/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent?all=1) will show all stemcells.

**Comment by AbelHu** [comment] 2017-03-15 02:49
@svrc-pivotal Could you try 3312.9? We guess that the issue may be caused by the same reason with sfdisk.

**Comment by AbelHu** [comment] 2017-03-15 02:49
@svrc-pivotal Could you try 3312.9? We guess that the issue may be caused by the same reason with sfdisk.

**Comment by svrc-pivotal** [comment] 2017-03-15 05:40
That was a typo,  apologies.  3363.9 and 3363.12.   I will try 3312.9 and report back.

**Comment by danhigham** [comment] 2017-05-07 16:45
Hey all, just encountered this issue with stemcell 3363.20, rolling back to 3312.9 worked fine. What's the latest version I can use without hitting this issue?

**Comment by AbelHu** [comment] 2017-05-08 01:51
@danhigham  You should be able to find `PartitionerType` is set to `parted` in `/var/vcap/bosh/agent.json` in the failed VM. I am not sure whether this is a same issue. Did you logon to the failed VM to check bosh-agent logs? We can help to investigate it if you share bosh-agent logs and task log with us.

**Comment by kamoljan** [comment] 2017-09-12 14:50
+1

**Closed** 2018-08-15 05:30 UTC
Labels: acknowledge, in-progress
