### ISSUE TITLE
Collecting diagnotics data should be opt-in, not opt-out

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry-incubator/bosh-azure-cpi-release#399] opened 2018-05-29 08:07 UTC
In [release 35.2.0](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/releases/tag/v35.2.0) you added two new features: collecting and reporting of diagnostics data and collecting boot logs for diagnostics. Those are *turned on by default*, which is exactly the opposite of what it should be. I'm no lawyer, but these kind of features should most likely always be *opt-in* (i.e. turned off by default), not *opt-out* (i.e. turned on by default). This is especially true in the light of new regulations, such as [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) and the like.

So, please, turn those two features *off by default*, such that users can decide if they want it or not.

**Comment by bingosummer** [comment] 2018-05-29 08:55
@voelzmo Thank you for raising the issue.

The collected data are whether the request to Azure ARM API fails or not. They are only for troubleshooting. Not related to marketing.

We value your point very highly. We will confirm it with the lawyer and keep you posted.

**Comment by cppforlife** [comment] 2018-05-29 21:09
@bingosummer there is also a concern about how fast these logs grow in the storage account since it doesnt get automatically cleaned up.

**Comment by voelzmo** [comment] 2018-05-30 06:49
Yes, @cppforlife is correct. We found also a screenshot (of a black screen) for every VM in the storage account. After 7 days, this amounted to 1.2TB of storage, which is quite unfortunate.

**Comment by bingosummer** [comment] 2018-05-30 10:01
We are trying to figure out why so many storage are used. Could you please share how many VMs do you have and how many containers in the storage account?

**Comment by NingKuang** [comment] 2018-06-02 06:16
Hi, @voelzmo @cppforlife We will turn it off by default. Please note, the diagnostic data helps trouble shooting issues during CF deployment and update, especially when the VM is deleted by Bosh. So we still suggest you turning it on before CF update, and clean up the storage account afterward. We will further exam the log size and automatic clean up options.  Thanks for the feedback!

**Comment by gossion** [comment] 2018-06-04 02:26
Hi @voelzmo , I am going to turn it off, however, can you help me to understand the 1.2TB of storage? how do you get the number?

I have a test environment with 18 VMs running for 6 days, as my observation from azure portal, the storage account with tag `type : bootdiagnostics` (which is for boot diagnostics) has data as below:

capacity: 1.79MB (usage)
total request: 2.23M (Metrics)
total egress: 365.84MB (Metrics)

The data are far from TB. And looking into bootdiagnostics-* containers, there are two files in each container: `.screenshot.bmp` and `.serialconsole.log`, which use about ~600KiB and ~40KiB, that means a VM boot diagnostics only use about 640 KB, I am quite confused why the usage can ammount to 1.2 `TB`, can you help me to clarify usage?

**Comment by bingosummer** [comment] 2018-06-04 05:42
Fixed in #400.

**Closed by bingosummer** 2018-06-04 05:42 UTC

**Comment by voelzmo** [comment] 2018-07-04 12:41
@gossion I guess our production environment is a bit bigger than your test environment. As I understand, the main driving forces of the storage account's size are how often VMs are started. This means you have two main influences:
* the number of instances
* How many compilation VMs are spun up, which again depends on
  * How many releases you deploy with how many packages
  * How oftern you roll in new stemcells

If we have ~1000 VMs, with a few releases and a decent number of packages and roll in a new stemcell within this 7 days, it amounts to quite some storage consumption.

A stupid quest from my side: The main space consumption seems to come from the screenshot. How useful is storing a screenshot of a linux server? What is supposed to show up there?

**Comment by gossion** [comment] 2018-07-05 02:00
Saying that you have 1000 VMs, the storage consumption should be about 640K * 1000 = 640,000 K = 625 M, and the amount will not increase too much by day because only 2 files are kept for a VM. To consume 1.2 TB, you need about 2000 (1.2 T / 625 M) new deployments, that can't be done in 7 days.
So I think 1.2 TB is unacceptable, maybe there is a bug about calculation of storage usage, can you help to file a ticket to Azure storage team to check the usage of your storage account?

For the screenshot of a Linux server, it is by designed on Azure. I don't have too much context, but from this [document](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/boot-diagnostics), I guess it can show some info that serial console can't, for example, the error message when serial console is not yet ready.

**Comment by bingosummer** [comment] 2018-07-05 02:59
Thanks @voelzmo for providing the information. It would be very helpful for us to understand why so many storage consumption is used, then we can improve CPI.

Where is the data `1.2TB/7 days` from? The expense report from Azure? I'd like to understand what `1.2TB` really means.
I checked the metrics of my diagnostic storage account in the last 24 hours. The result is:
![image](https://user-images.githubusercontent.com/4787647/42299901-42b8247c-8040-11e8-84f3-f550c74dc117.png)
The real consumption of the blobs is 36.6 MB. But for 24 hours, the `BLOB CAPACITY (SUM)` is `877.5 MB`, which is `36.6 * 24`. Is `1.2TB` also a sum of several days consumption? For example, `625 MB * 24 * 7 = 102 GB`. If so, considering many times of compiling packages or recreating VMs in your production environment, then 1.2 TB is possible.

Could you please check the metric of your diagnostic storage account? How much is the real consumption of the blobs?
