### ISSUE TITLE
Azure CPI token refresh timeout causing "Unknown CPI error" on vm_create

### ISSUE THREAD

**Issue by drhpivotal** [cloudfoundry-incubator/bosh-azure-cpi-release#239] opened 2017-02-09 19:24 UTC
### Versions (*please add them if you have more releases for this issue*)
CPI   Version: 62
BOSH  Version: 1.3262.24.0 (260.6.0) 
CF    Version: 246.0.6 
Diego Version: 0.1491.3

### Environment
- Azure Environment:
  - [X ] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureStack
  - [ ] Others:
- Location: EastUS2
- Subscription ID: {customer provided}
- Resource Group Name: {customer provided}

### Issue Details
During vm_create, Jobs are failing with an "Unknown CPI error" flag, which when examining the BOSH logs is caused by an Azure token refresh timeout against https://login.microsoftonline.com. This particular environment has granular NSG outbound rules defined allowing outbound connections to the range of IPs defined against this URL, however when additional IPs are added we begin to see timeout issues during certain CPI operations.

### Logs (*Please redact all sensitive information in your logs*)

I, [2017-02-09T17:13:47.048765 #4912]  INFO -- : get_token - trying to get/refresh Azure authentication token
D, [2017-02-09T17:13:47.048923 #4912] DEBUG -- : get_token - authentication_endpoint: https://login.microsoftonline.com/{guid}/oauth2/token?api-version=2015-06-15
D, [2017-02-09T17:13:47.049207 #4912] DEBUG -- : get_token - request.header:
D, [2017-02-09T17:13:47.049248 #4912] DEBUG -- :        accept-encoding = gzip;q=1.0,deflate;q=0.6,identity;q=0.3
D, [2017-02-09T17:13:47.049270 #4912] DEBUG -- :        accept = */*
D, [2017-02-09T17:13:47.049294 #4912] DEBUG -- :        user-agent = BOSH-AZURE-CPI
D, [2017-02-09T17:13:47.049317 #4912] DEBUG -- :        content-type = application/x-www-form-urlencoded
D, [2017-02-09T17:13:47.049359 #4912] DEBUG -- :        x-ms-client-request-id = {guid}
D, [2017-02-09T17:13:47.049390 #4912] DEBUG -- :        x-ms-return-client-request-id = true
W, [2017-02-09T17:14:47.050542 #4912]  WARN -- : get_token - Fail for an OpenTimeout. Will retry after 5 seconds.
D, [2017-02-09T17:14:52.050747 #4912] DEBUG -- : get_token - authentication_endpoint: https://login.microsoftonline.com/{guid}/oauth2/token?api-version=2015-06-15
D, [2017-02-09T17:14:52.051019 #4912] DEBUG -- : get_token - request.header:
D, [2017-02-09T17:14:52.051060 #4912] DEBUG -- :        accept-encoding = gzip;q=1.0,deflate;q=0.6,identity;q=0.3
D, [2017-02-09T17:14:52.051090 #4912] DEBUG -- :        accept = */*
D, [2017-02-09T17:14:52.051127 #4912] DEBUG -- :        user-agent = BOSH-AZURE-CPI
D, [2017-02-09T17:14:52.051154 #4912] DEBUG -- :        content-type = application/x-www-form-urlencoded
D, [2017-02-09T17:14:52.051191 #4912] DEBUG -- :        x-ms-client-request-id = {guid}
D, [2017-02-09T17:14:52.051226 #4912] DEBUG -- :        x-ms-return-client-request-id = true
D, [2017-02-09T17:14:52.317106 #4912] DEBUG -- : get_token - x-ms-client-request-id:
x-ms-request-id: {guid}
--
E, [2017-02-09 17:21:25 #65449] [create_missing_vm(diego_cell/{guid} (6)/27)]                                                                                    
ERROR -- DirectorJobRunner: error creating vm: Unknown CPI error 'Unknown' with message 'execution expired' in 'create_vm' CPI method

**Comment by AbelHu** [comment] 2017-02-10 03:08
From logs we got, it seems like to be caused by that a new IP A record had been added for the domain login.microsoftonline.com but the NSG rules was not updated.
According to our discussion, we will follow below items,

1. Check whether a new IP A record was added for login.microsoftonline.com;

1. Check whether there is a way to associate URLs/Domains to NSG but not ip addresses.

**Comment by AbelHu** [comment] 2017-02-15 03:31
Azure CPI will  log IP addresses next to all the URL call outs it makes in the bosh debug logs. This would make it significantly easier to determine specifically which IPs are timing out. After implementing this feature, we will close this issue.

**Comment by AbelHu** [comment] 2017-02-22 03:43
@drhpivotal For your questions,
#1. The answer is yes. That is the root cause you have confirmed.
#2. The only way is to add IPs to NSG for now. Some new features will be added in future.

**Comment by AbelHu** [comment] 2017-04-06 04:22
This issue should have been resolved.

**Closed by AbelHu** 2017-04-06 04:22 UTC
Labels: acknowledge
