### ISSUE TITLE
Unable to `cf push` example app - downloading buildpack failed

### ISSUE THREAD

**Issue by davidchua** [cloudfoundry-incubator/bosh-azure-cpi-release#214] opened 2016-10-07 01:16 UTC
```
cf version 6.14.1+dc6adf6-2015-12-22
cf: 238
example_manifest: single-vm
```

Hi guys,

I've successfully deployed CF on Azure with the help of the Azure ARM templates provided in this repo.

When attempting to do a `cf push` on the example 2048 application provided here:
https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/get-started/push-demo-app.md

I get stuck at the:

```
App game-2048 is a worker, skipping route creation
Uploading game-2048...
Uploading app files from: /home/moses/test-app/2048
Uploading 272.7K, 33 files
Done uploading
OK

Stopping app game-2048 in org default_organization / space tst as admin...
OK
Starting app game-2048 in org default_organization / space tst as admin...
```

`cf logs game-2048 --recent` shows:

```
Connected, dumping recent logs for app game-2048 in org default_organization / space tst as admin...

2016-10-07T01:12:27.19+0000 [API/0]      OUT Updated app with guid e626d705-8751-433d-a4fb-29a50e54257a ({"name"=>"game-2048", "buildpack"=>"staticfile_buildpack", "environment_json"=>"PRIVATE DATA HIDDEN"})
2016-10-07T01:12:33.06+0000 [API/0]      OUT Updated app with guid e626d705-8751-433d-a4fb-29a50e54257a ({"name"=>"game-2048", "buildpack"=>"staticfile_buildpack", "environment_json"=>"PRIVATE DATA HIDDEN"})
2016-10-07T01:12:38.42+0000 [API/0]      OUT Updated app with guid e626d705-8751-433d-a4fb-29a50e54257a ({"state"=>"STOPPED"})
2016-10-07T01:12:38.80+0000 [API/0]      OUT Updated app with guid e626d705-8751-433d-a4fb-29a50e54257a ({"state"=>"STARTED"})
2016-10-07T01:12:38.86+0000 [STG/0]      OUT Downloading staticfile_buildpack...
2016-10-07T01:12:38.88+0000 [STG/0]      OUT Downloading staticfile_buildpack failed
2016-10-07T01:12:50.79+0000 [API/0]      OUT Updated app with guid e626d705-8751-433d-a4fb-29a50e54257a ({"name"=>"game-2048", "buildpack"=>"staticfile_buildpack", "environment_json"=>"PRIVATE DATA HIDDEN"})
2016-10-07T01:12:57.44+0000 [API/0]      OUT Updated app with guid e626d705-8751-433d-a4fb-29a50e54257a ({"state"=>"STOPPED"})
2016-10-07T01:12:58.06+0000 [API/0]      OUT Updated app with guid e626d705-8751-433d-a4fb-29a50e54257a ({"state"=>"STARTED"})
2016-10-07T01:12:58.10+0000 [STG/0]      OUT Downloading staticfile_buildpack...
2016-10-07T01:12:58.11+0000 [STG/0]      OUT Downloading staticfile_buildpack failed
2016-10-07T01:13:31.58+0000 [API/0]      OUT Updated app with guid e626d705-8751-433d-a4fb-29a50e54257a ({"name"=>"game-2048", "buildpack"=>"staticfile_buildpack", "environment_json"=>"PRIVATE DATA HIDDEN"})
2016-10-07T01:13:38.02+0000 [API/0]      OUT Updated app with guid e626d705-8751-433d-a4fb-29a50e54257a ({"state"=>"STOPPED"})
2016-10-07T01:13:38.41+0000 [API/0]      OUT Updated app with guid e626d705-8751-433d-a4fb-29a50e54257a ({"state"=>"STARTED"})
2016-10-07T01:13:38.44+0000 [STG/0]      OUT Downloading staticfile_buildpack...
2016-10-07T01:13:38.45+0000 [STG/0]      OUT Downloading staticfile_buildpack failed
```

**Comment by bingosummer** [comment] 2016-10-07 09:02
@davidchua ,

Could you please verify the following items?

1. Did you use the [manifest](https://github.com/bingosummer/2048/blob/master/manifest.yml)?

  ```
  ---
  applications:
  - name: game-2048
    buildpack: staticfile_buildpack
  ```

  If so, I think, `App game-2048 is a worker, skipping route creation` should not be outputted when pushing the app.

2. Run `cf buildpacks`. The output should be:

  ```
  Getting buildpacks...

  buildpack                position   enabled   locked   filename
  java_buildpack           1          true      false    java-buildpack-v3.7.1.zip
  ruby_buildpack           2          true      false    ruby_buildpack-cached-v1.6.19.zip
  nodejs_buildpack         3          true      false    nodejs_buildpack-cached-v1.5.15.zip
  go_buildpack             4          true      false    go_buildpack-cached-v1.7.8.zip
  python_buildpack         5          true      false    python_buildpack-cached-v1.5.6.zip
  php_buildpack            6          true      false    php_buildpack-cached-v4.3.14.zip
  staticfile_buildpack     7          true      false    staticfile_buildpack-cached-v1.3.9.zip
  binary_buildpack         8          true      false    binary_buildpack-cached-v1.0.2.zip
  java_buildpack_offline   9          true      false    java-buildpack-offline-v3.7.1.zip
  ```

  You can see that `staticfile_buildpack` is installed by default.

3. Using the default manifest, `cf push` will use `staticfile_buildpack` from the output of `cf buildpacks`. The example output:

  ```
~/2048$ cf push
Using manifest file /home/azureuser/2048/manifest.yml

Updating app game-2048 in org default_organization / space azure as admin...
OK

Uploading game-2048...
Uploading app files from: /home/azureuser/2048
Uploading 272.7K, 33 files
Done uploading
OK

Stopping app game-2048 in org default_organization / space azure as admin...
OK

Starting app game-2048 in org default_organization / space azure as admin...
Downloading staticfile_buildpack...
Downloaded staticfile_buildpack
Creating container
Successfully created container
Downloading app package...
Downloaded app package (324.5K)
Downloading build artifacts cache...
Downloaded build artifacts cache (108B)
Staging...
-------> Buildpack version 1.3.9
Downloaded [file:///tmp/buildpacks/2657095acddce99388af663995fafd53/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_nginx_nginx-1.11.1-linux-x64.tgz]
-----> Using root folder
-----> Copying project files into public/
-----> Setting up nginx
Exit status 0
Staging complete
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (108B)
Uploaded droplet (2.9M)
Uploading complete

1 of 1 instances running

App started


OK

App game-2048 was started using this command `sh boot.sh`

Showing health and status for app game-2048 in org default_organization / space azure as admin...
OK
  ```

**Comment by davidchua** [comment] 2016-10-07 10:19
Hi,

I can confirm the manifest and buildpack.

When doing cf push, I get stuck at the starting app stage as in my original
post above.

**Comment by AbelHu** [comment] 2016-10-08 01:48
@davidchua Could you try to build a static buildpack, upload it and then try it?

1. Following the guide [Building the Buildpack](https://github.com/cloudfoundry/staticfile-buildpack) to build your buildpack
2. Update `staticfile_buildpack` in your manifest to use 'custom_node_buildpack'
3. Use `cf push` to push your app

**Comment by davidchua** [comment] 2016-10-09 11:48
Hi @AbelHu 

Did it:

```
moses@mosesvm:~/staticfile-buildpack$ BUNDLE_GEMFILE=cf.Gemfile bundle exec buildpack-packager --uncached
Uncached buildpack created and saved as /home/moses/staticfile-buildpack/staticfile_buildpack-v1.3.11.zip with a size of 44K
moses@mosesvm:~/staticfile-buildpack$ cf create-buildpack custom_node_buildpack staticfile_buildpack-v1.3.11.zip 1                           
Creating buildpack custom_node_buildpack...
OK

Uploading buildpack custom_node_buildpack...
Done uploading               
OK
moses@mosesvm:~/staticfile-buildpack$ cf buildpacks
Getting buildpacks...

buildpack                position   enabled   locked   filename   
custom_node_buildpack    1          true      false    staticfile_buildpack-v1.3.11.zip   
java_buildpack           2          true      false    java-buildpack-v3.7.1.zip   
ruby_buildpack           3          true      false    ruby_buildpack-cached-v1.6.19.zip   
nodejs_buildpack         4          true      false    nodejs_buildpack-cached-v1.5.15.zip   
go_buildpack             5          true      false    go_buildpack-cached-v1.7.8.zip   
python_buildpack         6          true      false    python_buildpack-cached-v1.5.6.zip   
php_buildpack            7          true      false    php_buildpack-cached-v4.3.14.zip   
staticfile_buildpack     8          true      false    staticfile_buildpack-cached-v1.3.9.zip   
binary_buildpack         9          true      false    binary_buildpack-cached-v1.0.2.zip   
java_buildpack_offline   10         true      false    java-buildpack-offline-v3.7.1.zip  
```

After doing a `cf push -b custom_node_buildpack --random-route`

It still failed at the `Downloading custom_node_buildpack failed` and time out.

```
Using manifest file /home/moses/test-app/2048/manifest.yml

Updating app game-2048 in org default_organization / space tst as admin...
OK

Creating route game-2048-unshy-rasistante.52.187.74.75.xip.io...
OK

Binding game-2048-unshy-rasistante.52.187.74.75.xip.io to game-2048...
OK

Uploading game-2048...
Uploading app files from: /home/moses/test-app/2048
Uploading 272.7K, 33 files
Done uploading               
OK

Starting app game-2048 in org default_organization / space tst as admin...
Downloading custom_node_buildpack...
Downloading custom_node_buildpack failed
```

**Comment by davidchua** [comment] 2016-10-11 02:35
Is there anything I can do to help troubleshoot this issue?

**Comment by AbelHu** [comment] 2016-10-11 09:15
@davidchua I use our template deploy a single cf in `southeast asia` and cannot reproduce your issue. Please try to deploy it with the template.

**Comment by AbelHu** [comment] 2016-10-13 03:26
Cannot reproduce it so close it.

**Closed by AbelHu** 2016-10-13 03:26 UTC
Labels: Done
